### ISSUE TITLE
Import or Export for bulk field additions

### ISSUE THREAD

**Issue by studioleland** [buddydev/bp-xprofile-custom-field-types#1]
Hello,

I have several use cases to add groups of fields at once.  We also have several conditional scenarios where will will be adding several hundred conditional fields based upon existing user selections.  Are there any methods to import BP fields?  I'm thinking some kind of csv or xml import?  This will save us many hours of manual input.  Curious for feedback.  Thank you!

**Comment by sbrajesh** [comment]
Hi,
Thank you for the question.

The plugin does not provide any import/export. It only supports registering custom field types.

Any WordPress plugin which allows you to import/export BuddyPress Xprofile data will work. 

Regards
Brajesh
