### ISSUE TITLE
File field doesn't save

### ISSUE THREAD

**Issue by AliAlmutawakel** [buddydev/bp-xprofile-custom-field-types#2]
Hello, 

I would like to submit a bug in the plugin called "BuddyPress Xprofile Custom Field Types" v1.1.1

Problem: The file field does not save the files.
- When editing in frontend profile editor, it will reload the page with all other fields updated and the file field is empty even though before saving, there was a file uploaded.
- Editing users in the backend "wp-admin/users.php" page. Under the extended tab. Uploading a file and saving it redirects to a 404 page. This only happens when there is a file field in the form.

Steps to reproduce:
- Add a new BuddyPress profile field of type "File"
- Navigate to a page to edit your profile information. You should see the new file field.
- Upload any file and hit save

I hope you can fix this issue get a fixed version available for download. For more information, please email me at info@yyls.info

**Comment by sbrajesh** [comment]
Hi,
Thank yo for reporting.
1. Are you using multisite or normal WordPress?
2. Are you on the latest version of BuddyPress/Xprofile Custom Field Types
3. Is there any secrity plugin/policy prohibiting upload?

Please let me know. I will check and get back to you.

**Comment by AliAlmutawakel** [comment]
I am on version 1.1.1 of xprofile custom profiles.
I have single site Wordpress 5.2.4 running OneSocial theme.

These are the plugins I have activated. None are security.
- WPBakery Page Builder
- WP Mail SMTP
- WordPress Importer
- User Menus
- Google Analytics for WordPress by MonsterInsights
- Eonet Manual User Approve
- BuddyPress Xprofile Custom Field Types
- BuddyPress
- BuddyBoss Products Updater
- BuddyBoss One Click Installer
- bbPress 
- All-in-One WP Migration

**Comment by sbrajesh** [comment]
Hi,
I am sorry I could not assist. I am not sure which of the above is causing the issue.
If you ever find the conflict, Please share and I will fix.

**Comment by AliAlmutawakel** [comment]
Hey,
I have disabled all plugins and left BuddyPress only. I still can't upload either a file or an image. There is no other plugin activated to conflict XProfile plugin. Neither register or anywhere else where I can use the custom field for uploading a file or an image works.

If you would like to see a demo on the website, email me at info@yyls.info. I'm open to any screen sharing session. I'm also a developer, so we can look at it together technically.

**Comment by sbrajesh** [comment]
Hi,
Please check your error log and also let me know if you are able to do normal upload.

Since you are a developer, May I suggest using xdebug to debug this? Sorry, I am not available for screen sharing.
