### ISSUE TITLE
Checkbox Acceptance type does not update state on dashboard profile edit page

### ISSUE THREAD

**Issue by troncali** [buddydev/bp-xprofile-custom-field-types#3]
The Checkbox Acceptance type sticks on value `1` when unchecked on the dashboard profile edit page.  This causes the field to always save as if it were checked, even if it previously wasn't.

The cause appears to be line 6 in `assets/js/bp-xprofile-custom-field-types.js`.  It uses `.editfield` as a parent selector, but that class does not exist on the parent on the dashboard profile edit page.

Possible fix: replace the selector with `.field_type_checkbox_acceptance`, which appears to be on both front and backend.

**Comment by sbrajesh** [comment]
Thank you for reporting and providing the solution.
It seems that the js was not need. While refactoring the old plugin to this one, we missed to cleanup that section.
I have fixed it now
https://github.com/buddydev/bp-xprofile-custom-field-types/commit/efd3ea4528f5983d0e7499c9a9317460d512e320

Will be available in next release.
